# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sage Elliott ðŸ¥‘
email: mailto:hello@sageelliott.com
description: I make things.
# baseurl: '/sage-blog'
url: "http://sageelliott.com" # the base hostname & protocol for your site
twitter: https://twitter.com/sagecodes
github: https://github.com/sagecodes
linkedin: https://www.linkedin.com/in/sageelliott
# Add about_me value
# Add Status value

# Build settings
markdown: kramdown
permalink: /:categories/:title/
